### ISSUE TITLE
ISSUE#0001

### ISSUE THREAD

**Issue by Ty-Irving** [NoahPinel/NoahPinel#3]

**Comment by NoahPinel** [comment]
Hey ty, 
Just cause you have the mathematical maturity of a grade 12 student doesn't mean you can comment this cringe stuff!
Cheers,
Npines.

**Comment by Ty-Irving** [comment]
Issue still isnt fixed git hub profile is still posting false information about being in third year although you havent even completed CPSC 219 a first year cpsc class LOL

**Comment by NoahPinel** [comment]
hmmm, won't we have classes together next sem? you will be a fourth year? hmmmmmm, why would a first-year be in 400 classes with a 4th year, interesting.....
